// Generated by CoffeeScript 1.9.3
(function() {
  this.Hello = (function() {
    var sayHello, variable;

    variable = 'hello';

    function Hello() {
      sayHello();
    }

    sayHello = function() {
      return $('body').append(variable);
    };

    return Hello;

  })();

}).call(this);
